language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -–t noronhaha/udemy -f ./client/Dockerfile.dev ./client

script:
  - docker run noronhaha/udemy npm test -- --coverage

after_success:
  -  docker build --t noronhaha/udemy_client ./client
  -  docker build --t noronhaha/udemy_nginx ./nginx
  -  docker build --t noronhaha/udemy_server ./server
  -  docker build --t noronhaha/udemy_worker ./worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket: "elasticbeanstalk-us-east-1-359129259698"
  bucket_path: "docker"
  on: 
    branch: master
  access_key: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key" 