language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -–t noronhaha/udemy -f ./client/Dockerfile.dev ./client

script:
  - docker run noronhaha/udemy npm test -- --coverage

after_success:
  -  docker build --t noronhaha/udemy_client ./client
  -  docker build --t noronhaha/udemy_nginx ./nginx
  -  docker build --t noronhaha/udemy_server ./server
  -  docker build --t noronhaha/udemy_worker ./worker
  
